# Generated by Django 4.0.5 on 2022-06-16 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre de categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del país')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'TIpo de documentos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electronico')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Apellidos')),
                ('identification', models.IntegerField(blank=True, null=True, verbose_name='Número de documento')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('type_house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartamento, unidad,edificio..')),
                ('neighbord', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.city', verbose_name='Municipio')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='País')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Departamento')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.typedocument', verbose_name='1.7. TIPO DOCUMENTO IDENTIDAD')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='True', max_length=200, null='True', verbose_name='Título')),
                ('minimum_age', models.IntegerField(blank=True, null=True, verbose_name='Edad minima')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Aforo')),
                ('ventacomida', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10, null=True, verbose_name='Venta de comida')),
                ('ventalicor', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10, null=True, verbose_name='Venta de Licor')),
                ('accesodiscapacitados', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10, null=True, verbose_name='Acceso a personas con discapacidad')),
                ('accesoembarazadas', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10, null=True, verbose_name='Acceso a embarazadas')),
                ('descripcion', models.TextField(blank='True', null='True', verbose_name='Descripción')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
