# Generated by Django 4.0.5 on 2022-06-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_acomodacion_eventos_acomodacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntosventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre de categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='puntoventa', verbose_name='Foto de local')),
                ('adress', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('horario', models.TextField(blank=True, null=True, verbose_name='Horario')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
