# Generated by Django 4.0.5 on 2022-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_puntosventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='etapa',
        ),
        migrations.AddField(
            model_name='eventos',
            name='puntosventa',
            field=models.ManyToManyField(blank=True, null=True, to='users.puntosventa', verbose_name='Punto de venta'),
        ),
    ]
