# Generated by Django 4.0.5 on 2022-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_eventos_etapa_eventos_puntosventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosventa',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='puntosventa',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='puntosventa',
            name='tiktok',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='TIktok'),
        ),
        migrations.AddField(
            model_name='puntosventa',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter'),
        ),
    ]
