# Generated by Django 4.0.5 on 2022-06-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_puntosventa_facebook_puntosventa_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre de convenciones')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Convencion',
                'verbose_name_plural': 'Convenciones',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=254, verbose_name='Cantidad idsponible')),
                ('asientos', models.CharField(max_length=254, verbose_name='Asientos')),
                ('price', models.CharField(max_length=254, verbose_name='Precio ')),
                ('leyenda', models.CharField(max_length=254, verbose_name='Leyenda')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('convencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.convencion', verbose_name='Localidad')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'BOleta',
                'verbose_name_plural': 'Boleta',
            },
        ),
        migrations.AddField(
            model_name='eventos',
            name='boleta',
            field=models.ManyToManyField(blank=True, null=True, to='users.boleta', verbose_name='Boletas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='boleta',
            field=models.ManyToManyField(blank=True, null=True, to='users.boleta', verbose_name='Boletas'),
        ),
    ]
