# Generated by Django 4.0.5 on 2022-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_convencion_boleta_eventos_boleta_profile_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='comprada',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10, null=True, verbose_name='Comprada'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='cantidadgeneral',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de boletas general'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='cantidadvendidas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de boletas general vendidas'),
        ),
    ]
