# Generated by Django 4.0.5 on 2022-06-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_boleta_comprada_eventos_cantidadgeneral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprada', models.CharField(blank=True, choices=[('PAGO', 'PAGO'), ('NOPAGO', 'NOPAGO')], max_length=10, null=True, verbose_name='Comprada')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.ManyToManyField(blank=True, null=True, to='users.boleta', verbose_name='Boletas')),
            ],
            options={
                'verbose_name': 'Carro de compra',
                'verbose_name_plural': 'Carros de compra',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.carshop'),
        ),
    ]
