# Generated by Django 4.0.5 on 2022-06-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_carshop_profile_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='apertura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apertura'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='final',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Horario final'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='inicio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Horario de inicio'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lugar'),
        ),
    ]
