# Generated by Django 4.0.5 on 2022-06-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_boleta_code_alter_profile_historialcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.city', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Departamento'),
        ),
    ]
