# Generated by Django 4.0.5 on 2022-06-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_eventos_city_eventos_country_eventos_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='localidad',
        ),
        migrations.AddField(
            model_name='localidad',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.eventos', verbose_name='Evento'),
        ),
    ]
