# Generated by Django 4.0.5 on 2022-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_eventos_boleta_remove_eventos_localidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='usuario/firma', verbose_name='Imagen del artista o subevento')),
                ('description', models.TextField(max_length=254, verbose_name='Descripción')),
                ('facebook', models.CharField(max_length=254, verbose_name='Facebook ')),
                ('instagram', models.CharField(max_length=254, verbose_name='Instagram')),
                ('tiktok', models.CharField(max_length=254, verbose_name='Tiktok')),
                ('twitter', models.CharField(max_length=254, verbose_name='Twitter')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='usuario/firma', verbose_name='Sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
