# Generated by Django 4.0.5 on 2022-06-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_artista_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='participante',
            field=models.ManyToManyField(blank=True, null=True, to='users.artista', verbose_name='Artistas'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='sponsor',
            field=models.ManyToManyField(blank=True, null=True, to='users.sponsor', verbose_name='Sponsor'),
        ),
    ]
