# Generated by Django 4.0.5 on 2022-07-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eventos',
            field=models.ManyToManyField(blank=True, null=True, related_name='Eventos', to='users.eventos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Persona Natural', 'Persona Natural'), ('Persona Juridica', 'Persona Juridica'), ('Caja', 'Caja')], max_length=100, null=True, verbose_name='Tipo de Persona:'),
        ),
    ]
